version: "3"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/tharlinshwe.social.crt:/etc/ssl/certs/tharlinshwe.social.crt:ro
      - ./nginx/tharlinshwe.social.key:/etc/ssl/private/tharlinshwe.social.key:ro

  api:
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      target: prod
      args:
        - NODE_ENV=production
    command: npm start
