version: "3"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/my-site.crt:/etc/ssl/certs/my-site.crt:ro
      - ./nginx/my-site.key:/etc/ssl/private/my-site.key:ro

  api:
    build:
      context: .
      target: prod
      args:
        - NODE_ENV=production
    command: npm start
