version: "3"

services:
  api:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo
      - nginx

  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  mongo-db:
