version: "3"

services:
  api:
    build:
      context: .
      target: dev
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
    command: npm run dev

  nginx:
    ports:
      - "4000:80"
