version: "3"

services:
  api:
    build:
      context: .
      target: test
      args:
        - NODE_ENV=test
    volumes:
      - ./:/app:ro
    command: npm run test

  nginx:
    ports:
      - "3000:80"
